/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mymainjavaproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leo
 */
public class AccountandDashBoard extends javax.swing.JFrame {

    /**
     * Creates new form AccountandDashBoard
     */
    public AccountandDashBoard() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        setTitle("Account Dashboard");
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        layeredpane = new javax.swing.JLayeredPane();
        accounthomepanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        accountpaymentpanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        accountpatientid = new javax.swing.JTextField();
        accountpatientname = new javax.swing.JTextField();
        accountpaymentdate = new com.toedter.calendar.JDateChooser();
        amountpaid = new javax.swing.JTextField();
        accountbalance = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        paymentpane = new javax.swing.JLayeredPane();
        master = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        holder = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        cardnumber = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        cvv = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        number = new javax.swing.JLabel();
        money = new javax.swing.JLabel();
        hold = new javax.swing.JLabel();
        cvcv = new javax.swing.JLabel();
        pnpn = new javax.swing.JLabel();
        visa = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        vamount = new javax.swing.JTextField();
        vholder = new javax.swing.JTextField();
        vcard = new javax.swing.JTextField();
        vmonth = new javax.swing.JComboBox<>();
        vyear = new javax.swing.JComboBox<>();
        vpin = new javax.swing.JTextField();
        vcvv = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        verve = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        veamount = new javax.swing.JTextField();
        veholder = new javax.swing.JTextField();
        vecard = new javax.swing.JTextField();
        vemonth = new javax.swing.JComboBox<>();
        veyear = new javax.swing.JComboBox<>();
        vepin = new javax.swing.JTextField();
        vecvv = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        accountbillpanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        billdate = new com.toedter.calendar.JDateChooser();
        bill_id = new javax.swing.JTextField();
        bill_amount = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        bill_name = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        billcardnumber = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        expiry = new javax.swing.JTextField();
        billcvv = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jButton16 = new javax.swing.JButton();
        billcardtype = new javax.swing.JComboBox<>();
        expensepanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        esid = new javax.swing.JTextField();
        esname = new javax.swing.JTextField();
        esamount = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator7 = new javax.swing.JSeparator();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        Date = new javax.swing.JTextField();
        viewpanel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ROYAL+ HOSPITAL");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/No Shellfish_52px_1.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/Administrator Male_52px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Accountant");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log out?");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 50, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 86));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/account3.jpg"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 140));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, -1, 136));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/Home_20px_1.png"))); // NOI18N
        jButton2.setText("HOME");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/Plus Math_20px.png"))); // NOI18N
        jButton3.setText("PAYMENT");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/Plus Math_20px.png"))); // NOI18N
        jButton4.setText("PAY BILLS");
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/Plus Math_20px.png"))); // NOI18N
        jButton5.setText("EXPENSES");
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jButton6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/Visible_20px.png"))); // NOI18N
        jButton6.setText("VIEW");
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 234, 1440, 47));

        layeredpane.setLayout(new java.awt.CardLayout());

        accounthomepanel.setBackground(new java.awt.Color(51, 51, 51));
        accounthomepanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        accounthomepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/account6.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        accounthomepanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 990, 440));

        layeredpane.add(accounthomepanel, "card2");

        accountpaymentpanel.setBackground(new java.awt.Color(51, 51, 51));
        accountpaymentpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        accountpaymentpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PAYMENT ENTRY FORM");
        accountpaymentpanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));
        accountpaymentpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 32, 910, 10));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Patient_ID:");
        accountpaymentpanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Full_Name:");
        accountpaymentpanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Payment_Date:");
        accountpaymentpanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Amount_Paid:");
        accountpaymentpanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Balance:");
        accountpaymentpanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        accountpatientid.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        accountpaymentpanel.add(accountpatientid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 50, 30));

        accountpatientname.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        accountpaymentpanel.add(accountpatientname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 130, -1));

        accountpaymentdate.setDateFormatString("yyy-MM-dd");
        accountpaymentpanel.add(accountpaymentdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 130, -1));

        amountpaid.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        accountpaymentpanel.add(amountpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 130, -1));

        accountbalance.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        accountpaymentpanel.add(accountbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 130, -1));
        accountpaymentpanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 282, 260, 10));

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("PAY");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        accountpaymentpanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("CANCEL");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        accountpaymentpanel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/MasterCard_48px.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        accountpaymentpanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, -1, 40));

        jLabel13.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 255, 0));
        jLabel13.setText("PAYMENT METHOD ");
        accountpaymentpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 102));
        jLabel14.setText("*");
        accountpaymentpanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 50, 30));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/Visa_48px.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        accountpaymentpanel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, 40));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/Bank Card Back Side_40px.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setContentAreaFilled(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        accountpaymentpanel.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        paymentpane.setLayout(new java.awt.CardLayout());

        master.setBackground(new java.awt.Color(51, 51, 51));
        master.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        master.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("MASTER CARD ");
        master.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/MasterCard_48px.png"))); // NOI18N
        master.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Account Holder:");
        master.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 100, 20));

        holder.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        holder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                holderKeyReleased(evt);
            }
        });
        master.add(holder, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 260, -1));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Card Number:");
        master.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        cardnumber.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        cardnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cardnumberKeyReleased(evt);
            }
        });
        master.add(cardnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 260, -1));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Expiry Date:");
        master.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        month.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MONTHS", "January", "February", "March", "April", "May", "Jun", "July", "August", "September", "October", "November", "December" }));
        master.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 100, -1));

        year.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEARS", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        master.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 90, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Amount:");
        master.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, 20));

        amount.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountKeyReleased(evt);
            }
        });
        master.add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 260, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Pin:");
        master.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, 20));

        pin.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        pin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pinKeyReleased(evt);
            }
        });
        master.add(pin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 90, -1));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("CVV:");
        master.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 40, 10));

        cvv.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        cvv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cvvKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cvvKeyReleased(evt);
            }
        });
        master.add(cvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 90, -1));

        jButton20.setBackground(new java.awt.Color(51, 51, 51));
        jButton20.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("PAY");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        master.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 90, -1));

        jButton21.setBackground(new java.awt.Color(51, 51, 51));
        jButton21.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("CANCEL");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        master.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 110, -1));

        number.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        number.setForeground(new java.awt.Color(0, 204, 204));
        master.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 140, 20));

        money.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        money.setForeground(new java.awt.Color(0, 204, 204));
        master.add(money, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 140, 20));

        hold.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        hold.setForeground(new java.awt.Color(0, 204, 204));
        master.add(hold, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 140, 20));

        cvcv.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cvcv.setForeground(new java.awt.Color(51, 255, 255));
        master.add(cvcv, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 50, 20));

        pnpn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pnpn.setForeground(new java.awt.Color(51, 255, 255));
        master.add(pnpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 20, 20));

        paymentpane.add(master, "card2");

        visa.setBackground(new java.awt.Color(51, 51, 51));
        visa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        visa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel39.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("VISA CARD");
        visa.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 130, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/Visa_48px.png"))); // NOI18N
        visa.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 30));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Amount:");
        visa.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Account Holder:");
        visa.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Card Number:");
        visa.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Expiry Date:");
        visa.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel45.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Pin:");
        visa.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("CVV:");
        visa.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        vamount.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        visa.add(vamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 280, -1));

        vholder.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        visa.add(vholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 280, -1));

        vcard.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        visa.add(vcard, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 280, -1));

        vmonth.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        vmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MONTHS", "January", "February", "March", "April", "May", "Jun", "July", "August", "September", "October", "November", "December" }));
        visa.add(vmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 120, -1));

        vyear.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        vyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEARS", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        visa.add(vyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 110, -1));

        vpin.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        visa.add(vpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 110, -1));

        vcvv.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        visa.add(vcvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 110, -1));

        jButton22.setBackground(new java.awt.Color(51, 51, 51));
        jButton22.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("PAY");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        visa.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 110, -1));

        jButton23.setBackground(new java.awt.Color(51, 51, 51));
        jButton23.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("CANCEL");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        visa.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        paymentpane.add(visa, "card3");

        verve.setBackground(new java.awt.Color(51, 51, 51));
        verve.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        verve.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("VERVE CARD");
        verve.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel48.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("Amount:");
        verve.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel49.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Account Holder:");
        verve.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(255, 255, 255));
        jLabel50.setText("Card Number:");
        verve.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel51.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Expiry Date:");
        verve.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        jLabel52.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Pin:");
        verve.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jLabel53.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("CVV:");
        verve.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, -1, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/Bank Card Back Side_40px.png"))); // NOI18N
        verve.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 30));

        veamount.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        verve.add(veamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 240, -1));

        veholder.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        verve.add(veholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 240, -1));

        vecard.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        verve.add(vecard, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 240, -1));

        vemonth.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        vemonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MONTHS", "January", "February", "March", "April", "May", "Jun", "July", "August", "September", "October", "November", "December" }));
        verve.add(vemonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 100, -1));

        veyear.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        veyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "YEARS", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        verve.add(veyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 80, -1));

        vepin.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        verve.add(vepin, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 90, -1));

        vecvv.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        verve.add(vecvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 80, -1));

        jButton12.setBackground(new java.awt.Color(51, 51, 51));
        jButton12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("PAY");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        verve.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 290, 90, -1));

        jButton24.setBackground(new java.awt.Color(51, 51, 51));
        jButton24.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText("CANCEL");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        verve.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        paymentpane.add(verve, "card4");

        accountpaymentpanel.add(paymentpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 690, 330));

        layeredpane.add(accountpaymentpanel, "card3");

        accountbillpanel.setBackground(new java.awt.Color(51, 51, 51));
        accountbillpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        accountbillpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("PAY BILL ENTRY FROM");
        accountbillpanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));
        accountbillpanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 960, 10));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Bill_ID:");
        accountbillpanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Amount:");
        accountbillpanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Payment_Date:");
        accountbillpanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Bill_Name:");
        accountbillpanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        billdate.setDateFormatString("yyy-MM-dd");
        accountbillpanel.add(billdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 50, 160, 30));

        bill_id.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        accountbillpanel.add(bill_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 60, 30));

        bill_amount.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        accountbillpanel.add(bill_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 150, -1));
        accountbillpanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 122, 950, 10));

        bill_name.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        bill_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose bill", "GOtv", "DSTV", "NEPA", "WATER", "INSURANCE", " " }));
        accountbillpanel.add(bill_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 160, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Card Number");
        accountbillpanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("MM / YY");
        accountbillpanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 50, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("CVV");
        accountbillpanel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 30, -1));

        billcardnumber.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        accountbillpanel.add(billcardnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 210, 30));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/MasterCard_48px.png"))); // NOI18N
        accountbillpanel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, 30));

        expiry.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        accountbillpanel.add(expiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 90, 30));

        billcvv.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        accountbillpanel.add(billcvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 110, 30));

        jButton13.setBackground(new java.awt.Color(0, 204, 204));
        jButton13.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("PAY");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        accountbillpanel.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 260, -1));
        accountbillpanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 362, 960, 20));

        jButton16.setBackground(new java.awt.Color(51, 51, 51));
        jButton16.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("RESET");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        accountbillpanel.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 190, -1));

        billcardtype.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        billcardtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARD TYPE", "VISA", "MASTER", "VERVE", "EXPRESS" }));
        accountbillpanel.add(billcardtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 110, 30));

        layeredpane.add(accountbillpanel, "card4");

        expensepanel.setBackground(new java.awt.Color(51, 51, 51));
        expensepanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        expensepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("EXPENSES ENTRY FORM");
        expensepanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));
        expensepanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 970, 10));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Expense_ID:");
        expensepanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Expense_Name:");
        expensepanel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Amount_Spent:");
        expensepanel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Expense_Date:");
        expensepanel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        esid.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        expensepanel.add(esid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 60, 30));

        esname.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        expensepanel.add(esname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 140, -1));

        esamount.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        expensepanel.add(esamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, -1));

        jTable2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expense_ID", "Expense_Name", "Amount_Spent", "Expense_Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        expensepanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 680, 380));
        expensepanel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 270, 10));

        jButton18.setBackground(new java.awt.Color(51, 51, 51));
        jButton18.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("ADD");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        expensepanel.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jButton19.setBackground(new java.awt.Color(51, 51, 51));
        jButton19.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("CANCEL");
        expensepanel.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        Date.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        expensepanel.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 140, -1));

        layeredpane.add(expensepanel, "card5");

        viewpanel.setBackground(new java.awt.Color(51, 51, 51));
        viewpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));
        viewpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/account7.jpg"))); // NOI18N
        viewpanel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 440));

        layeredpane.add(viewpanel, "card6");

        jPanel1.add(layeredpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 312, 990, 440));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/nurse.jpeg"))); // NOI18N
        jLabel30.setText("jLabel30");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 80, 230, 150));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton14.setBackground(new java.awt.Color(51, 51, 51));
        jButton14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton14.setForeground(java.awt.Color.white);
        jButton14.setText("BILLS PAID");
        jButton14.setBorder(null);
        jButton14.setContentAreaFilled(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 197, 35));

        jButton15.setBackground(new java.awt.Color(51, 51, 51));
        jButton15.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton15.setForeground(java.awt.Color.white);
        jButton15.setText("EXPENSES");
        jButton15.setBorder(null);
        jButton15.setContentAreaFilled(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 197, 35));

        jButton17.setBackground(new java.awt.Color(51, 51, 51));
        jButton17.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton17.setForeground(java.awt.Color.white);
        jButton17.setText("CASH PAYMENT");
        jButton17.setBorder(null);
        jButton17.setContentAreaFilled(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 197, 35));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, 230));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton25.setBackground(new java.awt.Color(51, 51, 51));
        jButton25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("VERVE CARD");
        jButton25.setBorder(null);
        jButton25.setContentAreaFilled(false);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 156, 31));

        jButton26.setBackground(new java.awt.Color(51, 51, 51));
        jButton26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setText("MASER CARD");
        jButton26.setBorder(null);
        jButton26.setContentAreaFilled(false);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 156, 31));

        jButton27.setBackground(new java.awt.Color(51, 51, 51));
        jButton27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("VISA CARD");
        jButton27.setBorder(null);
        jButton27.setContentAreaFilled(false);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 156, 31));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 330, 160, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1431, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        changePanel(accounthomepanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        changePanel(accountpaymentpanel);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        changePanel(accountbillpanel);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        changePanel(expensepanel);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        changePanel(viewpanel);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AccountantSignIn ac = new AccountantSignIn();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        changePayment(master);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        changePayment(visa);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        changePayment(verve);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
         String user = "root";
        String password = "";
         String url = "jdbc:mysql://localhost:3306/javaDatabase";
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection(url, user, password);
        String qry = "insert into Payment (Patient_ID, Full_Name, Payment_Date, Amount_Paid, Balance) values(?,?,?,?,?)";
        PreparedStatement pst = con.prepareStatement(qry);
        pst.setString(1, accountpatientid.getText());
        pst.setString(2, accountpatientname.getText());
        pst.setString(3, ((JTextField)accountpaymentdate.getDateEditor().getUiComponent()).getText());
        pst.setString(4, amountpaid.getText());
        pst.setString(5, accountbalance.getText());
        if(accountpatientid.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Patient ID field must not be empty");
        }
        else if(accountpatientname.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Full name field must not be empty");
        }
        else if(accountpaymentdate.getDate().equals(null)){
        JOptionPane.showMessageDialog(null, "You must enter payment date");
        }
        else if(amountpaid.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter the amount paid");
        }
        else if(accountbalance.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Please enter the balance");
        }
        else{
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Payment made successfully");
        accountpatientid.setText("");
        accountpatientname.setText("");
        accountpaymentdate.setDate(null);
        amountpaid.setText("");
        accountbalance.setText("");
        }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        accountpatientid.setText("");
        accountpatientname.setText("");
        accountpaymentdate.setDate(null);
        amountpaid.setText("");
        accountbalance.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
          try{
         String user = "root";
        String password = "";
         String url = "jdbc:mysql://localhost:3306/javaDatabase";
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection(url, user, password);
        String qry = "insert into MasterCard (Patient_ID, Amount, Account_Holder, Card_Number, Expiry_Month, Expiry_Year, pin, CVV) values(?,?,?,?,?,?,?,?)";
        PreparedStatement pst = con.prepareStatement(qry);
        pst.setString(1, accountpatientid.getText());
        pst.setString(2, amount.getText());
        pst.setString(3, holder.getText());
        pst.setString(4, cardnumber.getText());
        String value1 = month.getSelectedItem().toString();
        pst.setString(5, value1);
        String value2 = year.getSelectedItem().toString();
        pst.setString(6, value2);
        pst.setString(7, pin.getText());
        pst.setString(8, cvv.getText());
        if(amount.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter the amount");
        }
        else if(accountpatientid.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter patient ID");
        }
        else if(holder.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Card holder field must not be empty");
        }
        else if(cardnumber.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter card number");
        }
        else if(pin.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter the pin");
        }
        else if(cvv.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter the cvv");
        }
        else if(cardnumber.getText().trim().length() > 16 && cardnumber.getText().trim().length() < 16){
         JOptionPane.showMessageDialog(null, "Card number must not be greater or less than 16 digit");   
        }
        else{
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Payment made successfully");
        amount.setText("");
        holder.setText("");
        cardnumber.setText("");
        month.setSelectedIndex(0);
        year.setSelectedIndex(0);
        pin.setText("");
        cvv.setText("");
        accountpatientid.setText("");
        }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
         amount.setText("");
        holder.setText("");
        cardnumber.setText("");
        amountpaid.setText("");
        accountbalance.setText("");
        month.setSelectedIndex(0);
        year.setSelectedIndex(0);
        pin.setText("");
        cvv.setText("");
        accountpatientid.setText("");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
         try{
         String user = "root";
        String password = "";
         String url = "jdbc:mysql://localhost:3306/javaDatabase";
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection(url, user, password);
        String qry = "insert into VisaCard (Patient_ID, Amount, Account_Holder, Card_Number, Expiry_Month, Expiry_Year, pin, CVV) values(?,?,?,?,?,?,?,?)";
        PreparedStatement pst = con.prepareStatement(qry);
        pst.setString(1, accountpatientid.getText());
        pst.setString(2, vamount.getText());
        pst.setString(3, vholder.getText());
        pst.setString(4, vcard.getText());
        String value3 = vmonth.getSelectedItem().toString();
        pst.setString(5, value3);
        String value4 = vyear.getSelectedItem().toString();
        pst.setString(6, value4);
        pst.setString(7, vpin.getText());
        pst.setString(8, vcvv.getText());
        if(vamount.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter the amount");
        }
        else if(accountpatientid.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter patient ID");
        }
        else if(vholder.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Card holder field must not be empty");
        }
        else if(vcard.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter card number");
        }
        else if(vpin.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter the pin");
        }
        else if(vcvv.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter the cvv");
        }
        else{
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Payment made successfully");
        vamount.setText("");
        vholder.setText("");
        vcard.setText("");
        vmonth.setSelectedIndex(0);
        vyear.setSelectedIndex(0);
        vpin.setText("");
        vcvv.setText("");
        accountpatientid.setText("");
        }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        vamount.setText("");
        vholder.setText("");
        vcard.setText("");
        vmonth.setSelectedIndex(0);
        vyear.setSelectedIndex(0);
        vpin.setText("");
        vcvv.setText("");
        accountpatientid.setText("");
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        veamount.setText("");
        veholder.setText("");
        vecard.setText("");
        vemonth.setSelectedIndex(0);
        veyear.setSelectedIndex(0);
        vepin.setText("");
        vecvv.setText("");
        accountpatientid.setText("");
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
          try{
         String user = "root";
        String password = "";
         String url = "jdbc:mysql://localhost:3306/javaDatabase";
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection(url, user, password);
        String qry = "insert into VerveCard (Patient_ID, Amount, Account_Holder, Card_Number, Expiry_Month, Expiry_Year, pin, CVV) values(?,?,?,?,?,?,?,?)";
        PreparedStatement pst = con.prepareStatement(qry);
        pst.setString(1, accountpatientid.getText());
        pst.setString(2, veamount.getText());
        pst.setString(3, veholder.getText());
        pst.setString(4, vecard.getText());
        String value5 = vemonth.getSelectedItem().toString();
        pst.setString(5, value5);
        String value6 = veyear.getSelectedItem().toString();
        pst.setString(6, value6);
        pst.setString(7, vepin.getText());
        pst.setString(8, vecvv.getText());
        if(veamount.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter the amount");
        }
        else if(accountpatientid.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Card holder field must not be empty");
        }
        else if(veholder.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Card holder field must not be empty");
        }
        else if(vecard.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter card number");
        }
        else if(vepin.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter the pin");
        }
        else if(vecvv.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter the cvv");
        }
        else{
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Payment made successfully");
        veamount.setText("");
        veholder.setText("");
        vecard.setText("");
        vemonth.setSelectedIndex(0);
        veyear.setSelectedIndex(0);
        vepin.setText("");
        vecvv.setText("");
        accountpatientid.setText("");
        }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
         try{
         String user = "root";
        String password = "";
         String url = "jdbc:mysql://localhost:3306/javaDatabase";
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection(url, user, password);
        String qry = "insert into Pay_Bill (Amount, Payment_Date, Bill_Name, Card_Number, Card_Type, Expiry_Date, CVV) values(?,?,?,?,?,?,?)";
        PreparedStatement pst = con.prepareStatement(qry);
        //pst.setString(1, bill_id.getText());
        pst.setString(1, bill_amount.getText());
        pst.setString(2, ((JTextField)billdate.getDateEditor().getUiComponent()).getText());
        String value7 = bill_name.getSelectedItem().toString();
        pst.setString(3, value7);
        pst.setString(4, billcardnumber.getText());
        String value8 = billcardtype.getSelectedItem().toString();
        pst.setString(5, value8);
        pst.setString(6, expiry.getText());
        pst.setString(7, billcvv.getText());
//        if(bill_id.getText().trim().equals("")){
//        JOptionPane.showMessageDialog(null, "ID field must not be empty");
//        }
        if(bill_amount.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Amount field must not be empty");
        }
        else if(billcardnumber.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter card number");
        }
        else if(expiry.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter the expiration date");
        }
        else if(billcvv.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "You must enter the cvv");
        }
        else{
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Payment made successfully");
        bill_id.setText("");
        bill_amount.setText("");
        billdate.setDate(null);
        bill_name.setSelectedIndex(0);
        billcardnumber.setText("");
        billcardtype.setSelectedIndex(0);
        expiry.setText("");
        billcvv.setText("");
        }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        bill_id.setText("");
        bill_amount.setText("");
        billdate.setDate(null);
        bill_name.setSelectedIndex(0);
        billcardnumber.setText("");
        billcardtype.setSelectedIndex(0);
        expiry.setText("");
        billcvv.setText("");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model =(DefaultTableModel)jTable2.getModel();
        model.addRow(new Object[]{
        esid.getText(),
        esname.getText(),
        esamount.getText(),
        Date.getText(),
        });
        try{
         String user = "root";
            String password = "";
            String url = "jdbc:mysql://localhost:3306/javaDatabase";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(url, user, password);
            String query = "insert into Expenses(Expense_Name,Amount_Spent,Expense_Date)values(?,?,?)";
            PreparedStatement pst = con.prepareStatement(query);
            //pst.setString(1, esid.getText());
            pst.setString(1, esname.getText());
            pst.setString(2, esamount.getText());
            pst.setString(3, Date.getText());
//            if(esid.getText().trim().equals("")){
//            JOptionPane.showMessageDialog(null, "Expenses ID must not be empty");
//            }
           if(esname.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Expenses name must not be empty");
            }
            else if(esamount.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Amount field must not be empty");
            }
            else if(Date.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "Date field must not be empty");
            }
            else{
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully added");
            esid.setText("");
            esname.setText("");
            esamount.setText("");
            Date.setText("");
            }
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        AccountCashPay acp = new AccountCashPay();
        this.dispose();
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        AccountExpenses ae = new AccountExpenses();
        this.dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        AccountPayBill apb = new AccountPayBill();
        this.dispose();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        AccountantMasterCard amc = new AccountantMasterCard();
        this.dispose();
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        AccountantVisaCard avc = new AccountantVisaCard();
        this.dispose();
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        AccountantVerveCard avc = new AccountantVerveCard();
        this.dispose();
    }//GEN-LAST:event_jButton25ActionPerformed

    private void amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyReleased
        // TODO add your handling code here:
         String pattern = "[0-9.$,]{0,30}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(amount.getText());
        if(!match.matches()){
        money.setText("Incorrect format");
        }else{
        money.setText(null);
        }
    }//GEN-LAST:event_amountKeyReleased

    private void holderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_holderKeyReleased
        // TODO add your handling code here:
         String pattern = "[a-zA-Z0-9. ]{0,30}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(holder.getText());
        if(!match.matches()){
        hold.setText("Incorrect format");
        }else{
        hold.setText(null);
        }
    }//GEN-LAST:event_holderKeyReleased

    private void cardnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardnumberKeyReleased
        // TODO add your handling code here:
        String pattern = "[0-9]{0,30}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(cardnumber.getText());
        if(!match.matches()){
        number.setText("Incorrect format");
        }else{
        number.setText(null);
        }
    }//GEN-LAST:event_cardnumberKeyReleased

    private void cvvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvKeyPressed

    private void cvvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvKeyReleased
        // TODO add your handling code here:
             String pattern = "[0-9]{0,30}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(cvv.getText());
        if(!match.matches()){
        cvcv.setText("*");
        }else{
        cvcv.setText(null);
        }
    }//GEN-LAST:event_cvvKeyReleased

    private void pinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinKeyReleased
        // TODO add your handling code here:
             String pattern = "[0-9]{0,30}$";
        Pattern patt = Pattern.compile(pattern);
        Matcher match = patt.matcher(pin.getText());
        if(!match.matches()){
        pnpn.setText("*");
        }else{
        pnpn.setText(null);
        }
    }//GEN-LAST:event_pinKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountandDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountandDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountandDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountandDashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountandDashBoard().setVisible(true);
            }
        });
    }
            public void changePanel(JPanel panel)
    {
    layeredpane.removeAll();
   layeredpane.add(panel);
   layeredpane.repaint();
   layeredpane.revalidate();
    }
            public void changePayment(JPanel panel){
            paymentpane.removeAll();
            paymentpane.add(panel);
            paymentpane.repaint();
            paymentpane.revalidate();
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Date;
    private javax.swing.JTextField accountbalance;
    private javax.swing.JPanel accountbillpanel;
    private javax.swing.JPanel accounthomepanel;
    private javax.swing.JTextField accountpatientid;
    private javax.swing.JTextField accountpatientname;
    private com.toedter.calendar.JDateChooser accountpaymentdate;
    private javax.swing.JPanel accountpaymentpanel;
    private javax.swing.JTextField amount;
    private javax.swing.JTextField amountpaid;
    private javax.swing.JTextField bill_amount;
    private javax.swing.JTextField bill_id;
    private javax.swing.JComboBox<String> bill_name;
    private javax.swing.JTextField billcardnumber;
    private javax.swing.JComboBox<String> billcardtype;
    private javax.swing.JTextField billcvv;
    private com.toedter.calendar.JDateChooser billdate;
    private javax.swing.JTextField cardnumber;
    private javax.swing.JLabel cvcv;
    private javax.swing.JTextField cvv;
    private javax.swing.JTextField esamount;
    private javax.swing.JTextField esid;
    private javax.swing.JTextField esname;
    private javax.swing.JPanel expensepanel;
    private javax.swing.JTextField expiry;
    private javax.swing.JLabel hold;
    private javax.swing.JTextField holder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable2;
    private javax.swing.JLayeredPane layeredpane;
    private javax.swing.JPanel master;
    private javax.swing.JLabel money;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JLabel number;
    private javax.swing.JLayeredPane paymentpane;
    private javax.swing.JTextField pin;
    private javax.swing.JLabel pnpn;
    private javax.swing.JTextField vamount;
    private javax.swing.JTextField vcard;
    private javax.swing.JTextField vcvv;
    private javax.swing.JTextField veamount;
    private javax.swing.JTextField vecard;
    private javax.swing.JTextField vecvv;
    private javax.swing.JTextField veholder;
    private javax.swing.JComboBox<String> vemonth;
    private javax.swing.JTextField vepin;
    private javax.swing.JPanel verve;
    private javax.swing.JComboBox<String> veyear;
    private javax.swing.JTextField vholder;
    private javax.swing.JPanel viewpanel;
    private javax.swing.JPanel visa;
    private javax.swing.JComboBox<String> vmonth;
    private javax.swing.JTextField vpin;
    private javax.swing.JComboBox<String> vyear;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
