/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mymainjavaproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Leo
 */
public class ReceptionistSingIn extends javax.swing.JFrame {

    /**
     * Creates new form ReceptionistSingIn
     */
    public ReceptionistSingIn() {
        initComponents();
        setVisible(true);
        setResizable(false);
        setTitle("Receptionist Sign In");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        recept_username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        recept_password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        recept_enter = new javax.swing.JButton();
        recept_forgotpassword = new javax.swing.JButton();
        recept_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/Administrator Male_75px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 130, 180));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RECEPTIONIST SIGN IN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));

        recept_username.setBackground(new java.awt.Color(51, 51, 51));
        recept_username.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        recept_username.setForeground(new java.awt.Color(255, 255, 255));
        recept_username.setBorder(null);
        jPanel1.add(recept_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 150, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 150, 10));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        recept_password.setBackground(new java.awt.Color(51, 51, 51));
        recept_password.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        recept_password.setForeground(new java.awt.Color(255, 255, 255));
        recept_password.setBorder(null);
        jPanel1.add(recept_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 150, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 150, 10));

        recept_enter.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        recept_enter.setForeground(new java.awt.Color(255, 255, 255));
        recept_enter.setText("Enter");
        recept_enter.setBorder(null);
        recept_enter.setContentAreaFilled(false);
        recept_enter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recept_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recept_enterActionPerformed(evt);
            }
        });
        jPanel1.add(recept_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 70, -1));

        recept_forgotpassword.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        recept_forgotpassword.setForeground(new java.awt.Color(255, 255, 255));
        recept_forgotpassword.setText("Forgot Password");
        recept_forgotpassword.setBorder(null);
        recept_forgotpassword.setContentAreaFilled(false);
        recept_forgotpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recept_forgotpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recept_forgotpasswordActionPerformed(evt);
            }
        });
        jPanel1.add(recept_forgotpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        recept_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymainjavaproject/images/Reply All Arrow_20px_1.png"))); // NOI18N
        recept_back.setBorder(null);
        recept_back.setContentAreaFilled(false);
        recept_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        recept_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recept_backActionPerformed(evt);
            }
        });
        jPanel1.add(recept_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recept_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recept_enterActionPerformed
        // TODO add your handling code here:
         String username = recept_username.getText();
        String pass = recept_password.getText();
        try{
         String user = "root";
        String password = "";
        String url = "jdbc:mysql://localhost:3306/javaDatabase";
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection(url, user, password);
        String qry = "select * from AddReceptionist where Email_Address = ? and Password = ?";
        PreparedStatement pst = con.prepareStatement(qry);
        pst.setString(1, username);
        pst.setString(2, pass);
        
          ResultSet rs = pst.executeQuery();
        if (rs.next()){
        ReceptionistDashBoard db = new ReceptionistDashBoard();
        this.dispose();
        recept_username.setText("");
        recept_password.setText("");
        }
        else{
        JOptionPane.showMessageDialog(null, "Wrong username and password");
        recept_username.setText("");
        recept_password.setText("");
        }
      }
      catch(Exception e){
      JOptionPane.showMessageDialog(null, e);
      }
    }//GEN-LAST:event_recept_enterActionPerformed

    private void recept_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recept_backActionPerformed
        // TODO add your handling code here:
        DashBoard db = new DashBoard();
        this.dispose();
    }//GEN-LAST:event_recept_backActionPerformed

    private void recept_forgotpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recept_forgotpasswordActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Please meet your Admin for your password");
    }//GEN-LAST:event_recept_forgotpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionistSingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionistSingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionistSingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionistSingIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionistSingIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton recept_back;
    private javax.swing.JButton recept_enter;
    private javax.swing.JButton recept_forgotpassword;
    private javax.swing.JPasswordField recept_password;
    private javax.swing.JTextField recept_username;
    // End of variables declaration//GEN-END:variables
}
